name: Node.js CI and Deploy

on:
  push:
    branches:
      - main
      - live # Ajoutez la branche "live" ici pour déclencher le déploiement

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build --if-present

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.name "${{ secrets.GITHUB_ACTOR }}"
          git config --global user.email "${{ secrets.GITHUB_ACTOR }}@users.noreply.github.com"
          git checkout live
          rm -rf *
          mv dist/* .
          git add -A
          git commit -m "Deploy to GitHub Pages"
          git push origin live --force
